---
development:
  adapter: postgresql
  encoding: utf8
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  database: book_storm_development
  username: postgres
  password: 24373514
  pool: 5
test:
  adapter: postgresql
  encoding: utf8
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  database: book_storm_test
  username: postgres
  password: 24373514
  pool: 5
production:
  adapter: postgresql
  encoding: utf8
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  database: book_storm_preparing
  username: deployer
  password: 24373514
  pool: 5
